"""empty message

Revision ID: 1235437153ef
Revises: ccde0de2a6a4
Create Date: 2024-05-08 17:25:56.923571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1235437153ef'
down_revision = 'ccde0de2a6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'])
        batch_op.drop_column('worker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('worker_id')

    # ### end Alembic commands ###
