"""empty message

Revision ID: 8b4fba0d0e48
Revises: db579b3ce18d
Create Date: 2024-05-18 17:34:18.988916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4fba0d0e48'
down_revision = 'db579b3ce18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('worker', sa.VARCHAR(), nullable=True),
    sa.Column('rate', sa.FLOAT(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker')
    )
    # ### end Alembic commands ###
